/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.trainrec.android.presenter;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
